export const unitColors = {
  model: '#a0522d',
  on: 'green',
  event: '#00a300',
  effect: '#e13',
  source: 'geekblue',
  sample: 'purple',
  target: 'red',
  watch: 'orange',
  clock: 'blue',
  combine: 'darkcyan',
  restore: '#999',
  map: 'darkgreen',
  store: '#1890ff',
  function: '#888',
}
